name: Build

on:
  pull_request:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '19.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Uglify
      run: npm install uglify-js -g
    - name: Build
      run: uglifyjs --self -c -m -o dist/uglifyjs.js
   -name: Upload
   - uses: actions/upload-artifact@v3 
       with:
            name: dists
            path: dist/uglifyjs.js
